import { NextIntlClientProvider } from 'next-intl'
import { Metadata } from 'next'
import '../../styles/globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export function generateStaticParams() {
	return [{ locale: 'en' }, { locale: 'tr' }]
}

export default async function LocaleLayout({
	children,
	params: { locale },
}: {
	params: { locale: string }
	children: React.ReactNode
}) {
	let translation
	try {
		translation = (await import(`../../translation/${locale}.json`)).default
	} catch (error) {
		console.log(locale, error)
	}

	return (
		<html lang={locale} data-mode='dark'>
			<body className={inter.className}>
				<NextIntlClientProvider locale={locale} messages={translation}>
					{children}
				</NextIntlClientProvider>
			</body>
		</html>
	)
}
